[profile.default]
src = "contracts"
out = "out"
test = "test"
script = "script"
libs = ["node_modules", "lib"]
solc_version = "0.8.30"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = false
int_types = "long"

[rpc_endpoints]
sepolia = "${SOURCE_CHAIN_RPC_URL}"
creditcoin_testnet = "${CREDITCOIN_RPC_URL}"
